package com.csye6225.assignment3.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_id
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.first_name
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_name
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email_address
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_created
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private Date accountCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_updated
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private Date accountUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_id
     *
     * @return the value of account.user_id
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_id
     *
     * @param userId the value for account.user_id
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.first_name
     *
     * @return the value of account.first_name
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.first_name
     *
     * @param firstName the value for account.first_name
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_name
     *
     * @return the value of account.last_name
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_name
     *
     * @param lastName the value for account.last_name
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email_address
     *
     * @return the value of account.email_address
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email_address
     *
     * @param emailAddress the value for account.email_address
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_created
     *
     * @return the value of account.account_created
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public Date getAccountCreated() {
        return accountCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_created
     *
     * @param accountCreated the value for account.account_created
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setAccountCreated(Date accountCreated) {
        this.accountCreated = accountCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_updated
     *
     * @return the value of account.account_updated
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public Date getAccountUpdated() {
        return accountUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_updated
     *
     * @param accountUpdated the value for account.account_updated
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    public void setAccountUpdated(Date accountUpdated) {
        this.accountUpdated = accountUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jan 29 15:50:57 EST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", firstName=").append(firstName);
        sb.append(", lastName=").append(lastName);
        sb.append(", emailAddress=").append(emailAddress);
        sb.append(", password=").append(password);
        sb.append(", accountCreated=").append(accountCreated);
        sb.append(", accountUpdated=").append(accountUpdated);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}