package com.csye6225.assignment3.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class AttachedFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attached_file.file_id
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attached_file.file_name
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attached_file.url
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attached_file.upload_date
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private Date uploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attached_file.file_md5
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private String fileMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attached_file.file_size
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attached_file.file_id
     *
     * @return the value of attached_file.file_id
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attached_file.file_id
     *
     * @param fileId the value for attached_file.file_id
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attached_file.file_name
     *
     * @return the value of attached_file.file_name
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attached_file.file_name
     *
     * @param fileName the value for attached_file.file_name
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attached_file.url
     *
     * @return the value of attached_file.url
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attached_file.url
     *
     * @param url the value for attached_file.url
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attached_file.upload_date
     *
     * @return the value of attached_file.upload_date
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attached_file.upload_date
     *
     * @param uploadDate the value for attached_file.upload_date
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attached_file.file_md5
     *
     * @return the value of attached_file.file_md5
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attached_file.file_md5
     *
     * @param fileMd5 the value for attached_file.file_md5
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attached_file.file_size
     *
     * @return the value of attached_file.file_size
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attached_file.file_size
     *
     * @param fileSize the value for attached_file.file_size
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileName=").append(fileName);
        sb.append(", url=").append(url);
        sb.append(", uploadDate=").append(uploadDate);
        sb.append(", fileMd5=").append(fileMd5);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}