package com.csye6225.assignment3.mbg.mapper;

import com.csye6225.assignment3.mbg.model.AttachedFile;
import com.csye6225.assignment3.mbg.model.AttachedFileExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface AttachedFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    long countByExample(AttachedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int deleteByExample(AttachedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int insert(AttachedFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int insertSelective(AttachedFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    List<AttachedFile> selectByExample(AttachedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    AttachedFile selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int updateByExampleSelective(@Param("record") AttachedFile record, @Param("example") AttachedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int updateByExample(@Param("record") AttachedFile record, @Param("example") AttachedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int updateByPrimaryKeySelective(AttachedFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attached_file
     *
     * @mbg.generated Wed Mar 18 08:40:42 EDT 2020
     */
    int updateByPrimaryKey(AttachedFile record);
}