version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      - save_cache: # Caches dependencies with a cache key
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-demo-workflows
      
#...                          
workflows:
  version: 2
  pr-check: # name of your workflow
    jobs:
      - pr_check
